"""Added collateral_id column

Revision ID: 0f9e6d251565
Revises: 
Create Date: 2023-11-24 09:43:22.072074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9e6d251565'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_form_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collateral_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_collateral_id', 'collaterals', ['collateral_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('loan_form_payment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_collateral_id', type_='foreignkey')
        batch_op.drop_column('collateral_id')
    

    op.create_table('equity_payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('exact_date', sa.DATETIME(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('equity_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('ref_no', sa.VARCHAR(), nullable=True),
    sa.Column('balance', sa.FLOAT(), nullable=True),
    sa.Column('bank_id', sa.INTEGER(), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['equity_id'], ['equities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equity_payments', schema=None) as batch_op:
        batch_op.create_index('ix_equity_payments_equity_id', ['equity_id'], unique=False)
        batch_op.create_index('ix_equity_payments_bank_id', ['bank_id'], unique=False)

    op.create_table('equities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('balance', sa.FLOAT(), nullable=True),
    sa.Column('balance_bfd', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
