"""edited collateral_id column

Revision ID: 7cdb150aae4c
Revises: 0f9e6d251565
Create Date: 2023-11-25 09:02:30.913641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cdb150aae4c'
down_revision = '0f9e6d251565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaterals', schema=None) as batch_op:
        batch_op.drop_index('ix_collaterals_loan_id')
        # batch_op.drop_constraint("fk_loan_id", type_='foreignkey')
        batch_op.drop_column('loan_id')

    with op.batch_alter_table('guarantor_contribution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collateral_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_collateral_id', 'collaterals', ['collateral_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('guarantor_contribution', schema=None) as batch_op:
        batch_op.drop_constraint('fk_collateral_id', type_='foreignkey')
        batch_op.drop_column('collateral_id')

    with op.batch_alter_table('collaterals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key("fk_loan_id", 'loans', ['loan_id'], ['id'])
        batch_op.create_index('ix_collaterals_loan_id', ['loan_id'], unique=False)

    # ### end Alembic commands ###
